### ISSUE TITLE
Error when opening in Raspbian 12

### ISSUE THREAD

**Issue by Slainester** [trelby/trelby#41] opened 2024-10-25 11:51 UTC
After I installed Trelby on a Raspberry 3 with Raspbian 12, it would not open at all when I clicked the icon.
So I opened it via Terminal: 
$ trelby
It brought up an error: ModuleNotFoundError: No module named 'trelby'.
The error referred to the path /usr/bin/trelby line 5.
When opening that file with nano:

$sudo nano /usr/bin/trelby

I found that there is a doubled pathname in the entry in line 3:

sys.path.insert(0, "/usr/share/trelby//usr/share/trelby/src")

After correcting it to:

sys.path.insert(0, "/usr/share/trelby/src")

and saving the trelby file, Trelby now opens as expected.

**Comment by limburgher** [comment] 2024-10-25 20:34
Duplicate of #27 , same problem.

**Comment by Serjicalclic** [comment] 2024-11-24 23:10
@Slainester Thank you! I'm not linux savvy, and after a few hours of research, your post saved me.

**Comment by limburgher** [comment] 2024-12-12 22:52
Try the PyPi version: pip install trelby.

**Comment by limburgher** [comment] 2024-12-12 22:54
Try the PyPi version: pip install trelby.

**Comment by limburgher** [comment] 2024-12-31 22:35
Resolved in 2.4.11 and 2.4.12, available https://build.opensuse.org/package/show/home:gwync/trelby

**Closed by limburgher** 2024-12-31 22:35 UTC
