### ISSUE TITLE
2.4.10 Scrolling not working in X11 or Wayland

### ISSUE THREAD

**Issue by rcentros** [trelby/trelby#29] opened 2024-09-16 19:37 UTC
Tested on Linux Mint 21.3, LM 22 and Fedora 39.

Scrolling is not working. In 2.4.10 when attempting to scroll up or down, Trelby will scroll slightly than kind of "bounce back." Will never scroll past a certain point. Worked in 2.4.9 on all three machines in both X11 and Wayland.

(Sorry to be a pest today. This is the first time I got to test 2.4.10.)

**Comment by limburgher** [comment] 2024-09-16 19:40
I see this on Fedora 40 as well. It's like scrolling won't leave the current page, but arrow keys are fine. @janopae this looks like a scrolling regression, can you take a look?

**Comment by janopae** [comment] 2024-09-27 13:26
Hey, thanks for asking me :)

I currently short on time, but you could help me by investigating on which exact commit the problem started.

**Comment by limburgher** [comment] 2024-09-27 15:53
I git bisected and it's bee7537c4cf97319403763aaa7f95d31f7778b88, your commit message for which suggests the most likely fix.

**Comment by limburgher** [comment] 2024-12-31 22:10
Please test what I just pushed to master. If it works for you as well as it does for me, it will be 2.4.12.

**Comment by limburgher** [comment] 2024-12-31 22:36
Fixed with 2.4.12

**Closed by limburgher** 2024-12-31 22:36 UTC

**Comment by janopae** [comment] 2025-01-02 15:04
The problem was that I could never reproduce this issue. It would be nice if someone found a way to reproduce it, we'd probably never be able to merge https://github.com/limburgher/trelby/pull/85 or fix https://github.com/limburgher/trelby/issues/20 in any other way.

**Comment by limburgher** [comment] 2025-01-02 15:06
Interesting. I wonder if it's a python or module version difference.
